graph TD

    subgraph Presentation[Presentation Layer]
        EatTogether.Contracts
        EatTogether.WebApi
    end

    subgraph Infrastructure[Infrastructure Layer]
        EatTogether.Infrastructure
    end

    subgraph Application[Application Layer]
        EatTogether.Application
    end

    subgraph Domain[Domain Layer]
        EatTogether.Domain
    end

    Presentation --> Application
    Infrastructure --> Application
    Application --> Domain